# Generated by Django 5.0.7 on 2024-12-24 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nextdoor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
